#FROM registry.access.redhat.com/ubi9/ubi
FROM  almalinux:9.4

RUN   dnf update -y &&  dnf group install -y 'Development Tools' && \
      dnf install -y gsl-devel flex bison gcc-c++  gtk3-devel cairo-devel \
      pango-devel gdk-pixbuf2-devel fftw-devel libpng-devel diffutils \
      wget lz4 lz4-devel libcurl-devel openssh-clients krb5-workstation \
      gcc-gfortran
RUN   sed -i -E '/default_ccache_name/s//# default_ccache_name/g' /etc/krb5.conf && \
      sed -i -E '/#\s+default_realm\s* =\s*EXAMPLE.COM\s*/s//default_realm = DESY.DE/g' /etc/krb5.conf
RUN   if [ ! -d ~/.ssh ]; then \
          mkdir -p ~/.ssh; \
          chmod 700 ~/.ssh;\
      fi; \
      wget -q https://wims.desy.de/system/ALL_afs/etc/ssh_known_hosts2 -O ~/.ssh/known_hosts
