#!/bin/sh

PROCESS_HKL=$1

cat > process_hkl_check_4.stream << EOF
CrystFEL stream format 2.3
Command line: indexamajig -i dummy.lst -o dummy.stream --kraken=prawn
----- Begin geometry file -----
photon_energy = 9000 eV
panel/min_fs = 0
panel/min_ss = 0
panel/max_fs = 1023
panel/max_ss = 1023
panel/fs = x
panel/ss = y
panel/corner_x = -100
panel/corner_y = -100
panel/clen = 50 mm
panel/res = 1000000
panel/adu_per_photon = 1
panel/data = /data/data_array
----- End geometry file -----
----- Begin chunk -----
Image filename: dummy.h5
photon_energy_eV = 2000.0
--- Begin crystal
Cell parameters 27.74398 27.84377 16.90346 nm, 88.53688 91.11774 118.75944 deg
astar = -0.0283891 +0.0149254 -0.0257273 nm^-1
bstar = -0.0068281 +0.0403989 -0.0005196 nm^-1
cstar = +0.0406926 +0.0052233 -0.0426520 nm^-1
Reflections measured after indexing
   h    k    l          I   sigma(I)       peak background  fs/px  ss/px panel
   1   0   0       100.00       0.00      100.0        0.0  938.0  629.0 panel
End of reflections
--- End crystal
----- End chunk -----
EOF

cat > process_hkl_check_4_ans.hkl << EOF
CrystFEL reflection list version 2.0
Symmetry: 1
   h    k    l          I    phase   sigma(I)   nmeas
EOF

$PROCESS_HKL -i process_hkl_check_4.stream -o process_hkl_check_4.hkl --no-polarisation
if [ $? -ne 0 ]; then
	exit 1;
fi
sed -n '/End of reflections/q;p' process_hkl_check_4.hkl > tempf.hkl
mv tempf.hkl process_hkl_check_4.hkl
diff process_hkl_check_4.hkl process_hkl_check_4_ans.hkl
if [ $? -ne 0 ]; then
	exit 1
fi
rm -f process_hkl_check_4.stream process_hkl_check_4.hkl process_hkl_check_4_ans.hkl
exit 0
