electron_voltage = /LCLS/electron_energy V
clen = 50 mm
panel/min_fs = 0
panel/min_ss = 1
panel/max_fs = 0
panel/max_ss = 1
panel/fs = x
panel/ss = y
panel/corner_x = -100
panel/corner_y = -100
panel/res = 1000000
panel/adu_per_photon = 1
panel/data = /data/data_array
