.\"
.\" compare_hkl man page
.\"
.\" Copyright © 2012 Thomas White <taw@physics.org>
.\"
.\" Part of CrystFEL - crystallography with a FEL
.\"

.TH COMPARE_HKL 1
.SH NAME
compare_hkl \- compare reflection data
.SH SYNOPSIS
.PP
\fBcompare_hkl\fR \fR [\fIoptions\fR] \fB...\fR \fIfile1.hkl\fR \fIfile2.hkl\fR
.PP
\fBcompare_hkl --help\fR

.SH DESCRIPTION
compare_hkl compares two sets of reflection data and calculates figures of merit such as R-factors.  Several figures of merit will be displayed on the command line.  Figures of merit can also be calculated in resolution shells.  Reflections will be considered equivalent according to your choice of point group.  The ratios of the reflections can be written to a new file, perhaps to look for systematic effects.

.SH OPTIONS
.PD 0
.IP \fB-y\fR \fpointgroup\fR
.IP \fB--symmetry=\fR\fIpointgroup\fR
.PD
Specify the symmetry of the reflections.  The symmetry must be the same for both lists of reflections.  Default: 1 (no symmetry).

.PD 0
.IP \fB-p\fR \fIunitcell.pdb\fR
.IP \fB--pdb=\fR\fIunitcell.pdb\fR
.PD
Specify the name of the PDB file containing at least a CRYST1 line describing the unit cell.

.PD 0
.IP \fB--rmin=\fR\fI1/d\fR
.PD
Fix the lower resolution limit for the resolutions shells, as 1/d in m^-1.  Reflections outside the specified resolution range will still be included in the calculation of overall figures of merit.

.PD 0
.IP \fB--rmax=\fR\fI1/d\fR
.PD
Fix the upper resolution limit for the resolutions shells, as 1/d in m^-1  Reflections outside the specified resolution range will still be included in the calculation of overall figures of merit.

.PD 0
.IP \fB--sigma-cutoff=\fR\fIn\fR
.PD
Discard reflections with I/sigma(I) < \fIn\fR.  Default: -infinity (no cutoff).

.PD 0
.IP \fB--shells=\fR\fIFoM\fR
.PD
Calculate \fIFoM\fR in resolution shells.  Possible figures of merit for \fIFoM\fR are:
.RS
.IP \fBRsplit\fR
.PD
2^(-0.5) * sum(I1-kI2) / [ 0.5*sum(I1+kI2) ]
.IP \fBR1f\fR
.PD
sum(F1-kF2) / sum(f1)
.IP \fBR1i\fR
.PD
sum(I1-kI2) / sum(I1)
.PP
I1 and I2 are the intensities of the same reflection in both reflection lists.  F1 and F2 are the square roots of the intensities.  Negative intensity values are discarded if R1f is used.  The scale factor, k, is chosen to minimise the R-factor in all cases.
.RE

.PD 0
.IP \fB-p\fR \fIunitcell.pdb\fR
.IP \fB--pdb=\fR\fIunitcell.pdb\fR
.PD
Specify the name of the PDB file containing at least a CRYST1 line describing the unit cell.  This is required if \fB--shells\fR is used.

.PD 0
.IP \fB-o\fR \fIfilename\fR
.IP \fB--ratio=\fR\fIfilename\fR
.PD
Write the ratios of the reflection intensities to \fIfilename\fR.  The ratio file will also be a CrystFEL reflection list (suitable for use with, for example, \fBrender_hkl\R), but the intensities column in the file will actually contain the ratios of intensities.

.SH AUTHOR
This page was written by Thomas White.

.SH REPORTING BUGS
Report bugs to <taw@physics.org>, or visit <http://www.desy.de/~twhite/crystfel>.

.SH COPYRIGHT AND DISCLAIMER
Copyright © 2012 Deutsches Elektronen-Synchrotron DESY, a research centre of the Helmholtz Association.
.P
compare_hkl, and this manual, are part of CrystFEL.
.P
CrystFEL is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.P
CrystFEL is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License along with CrystFEL.  If not, see <http://www.gnu.org/licenses/>.

.SH SEE ALSO
.BR crystfel (7),
.BR check_hkl (1),
.BR render_hkl (1)
