.\"
.\" partialator man page
.\"
.\" Copyright © 2012-2015 Deutsches Elektronen-Synchrotron DESY,
.\"                       a research centre of the Helmholtz Association.
.\"
.\" Part of CrystFEL - crystallography with a FEL
.\"

.TH PARTIALATOR 1
.SH NAME
partialator \- scaling and post-refinement of partial reflections
.SH SYNOPSIS
.PP
.B partialator
\fB-i\fR \fIinput.stream\fR
\fB-o\fR \fIoutput.hkl\fR
\fB-y\fR \fIpointgroup\fR
[\fBoptions\fR] \fB...\fR
.PP
.B partialator
\fB--help\fR

.SH DESCRIPTION
\fBpartialator\fR merges reflections by scaling and post refinement, accounting
for the partialities of the reflections.  That means that it models the geometry
of diffraction for each pattern (crystal orientation, unit cell parameters,
X-ray bandwidth and so on) and attempts to optimise the geometrical parameters
to make the fully integrated intensities calculated using the model agree as
closely as possible between the many patterns.
.PP
This program is \fIexperimental\fR in this version of CrystFEL.  It is not yet
considered ready for processing experimental data.

.SH OPTIONS
.PD 0
.IP "\fB-i\fR \fIfilename\fR"
.IP \fB--input=\fR\fIfilename\fR
.PD
Give the name of the input stream.

.PD 0
.IP "\fB-o\fR \fIfilename\fR"
.IP \fB--output=\fR\fIfilename\fR
.PD
Give the name of the output file.  The default is
\fB--output=partialator.hkl\fR.

.PD 0
.IP "\fB-y\fR \fIpointgroup\fR"
.IP \fB--symmetry=\fR\fIpointgroup\fR
.PD
Merge according to symmetry \fIpointgroup\fR.

.PD 0
.IP "\fB-n\fR \fIn\fR"
.IP \fB--iterations=\fR\fIn\fR
.PD
Run \fIn\fR cycles of scaling and post refinement.

.PD 0
.IP \fB--no-scale\fR
.PD
Fix all the overall scaling factors to be unity.

.PD 0
.IP "\fB-m\fR \fImodel\fR"
.IP \fB--model=\fR\fImodel\fR
.PD
Specify the partiality model.  See the list below for possible choices.

.PD 0
.IP "\fB-j\fR \fIn\fR"
.PD
Run \fIn\fR analyses in parallel.

.PD 0
.IP \fB--no-polarisation\fR
.PD
Disable the polarisation correction.

.PD 0
.IP \fB--max-adu=\fR\fIn\fR
.PD
Include reflections only if their peak values were less than \fIn\fR.  That means, \fIn\fR is the saturation value of the detector.  The default is infinity, i.e. no cutoff.

.PD 0
.IP \fB--min-measurements=\fR\fIn\fR
.PD
Include a reflection in the output only if it appears at least least \fIn\fR times.  The default is \fB--min-measurements=2\fR.

.SH PARTIALITY MODELS

The available partiality models are:

.IP \fBscsphere\fR
.PD
The volume of intersection between a sphere centered on each reciprocal lattice
point and the part of reciprocal space excited by the Ewald sphere taking into
account the finite bandwidth and convergence angle.  A "source coverage factor"
will be included to take into account the spectral brightness of the effective
source for the reflection.

This model is similar to that described in Acta Cryst. D69 (2013) p1231-1240,
and in Phil. Trans. Roy. Soc. B 369 (2014) 20130330, except that the "Lorentz
factor" described there is no longer treated as a separate factor.


.IP \fBscgaussian\fR
.PD
As \fBscsphere\fR, except that the shape of the scattering density centered on
each reciprocal lattice point is taken to be a 3D Gaussian distribution instead
of a sphere.  The standard deviation of the distribution will be the profile
radius (determined by indexamajig) divided by 2.6.

.IP \fBunity\fR
.PD
Fix all partialities at 1.


.SH BUGS
This program is \fIexperimental\fR in this version of CrystFEL.  It is not
yet considered ready for processing experimental data.  Your pet kitten may
explode if you attempt to solve a structure using intensities calculated by this
program.


.SH AUTHOR
This page was written by Thomas White.

.SH REPORTING BUGS
Report bugs to <taw@physics.org>, or visit <http://www.desy.de/~twhite/crystfel>.

.SH COPYRIGHT AND DISCLAIMER
Copyright © 2012-2015 Deutsches Elektronen-Synchrotron DESY, a research centre of the Helmholtz Association.
.P
partialator, and this manual, are part of CrystFEL.
.P
CrystFEL is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.P
CrystFEL is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License along with CrystFEL.  If not, see <http://www.gnu.org/licenses/>.

.SH SEE ALSO
.BR crystfel (7),
.BR indexamajig (1),
.BR process_hkl (1),
.BR partial_sim (1),
.BR crystfel_geometry (5).
