.\"
.\" pattern_sim man page
.\"
.\" (c) 2009-2011 Thomas White <taw@physics.org>
.\"
.\" Part of CrystFEL - crystallography with a FEL
.\"

.TH PATTERN\_SIM 1
.SH NAME
pattern\_sim \- Simulation of nanocrystallographic diffraction patterns
.SH SYNOPSIS
.PP
.B pattern\_sim
[options]

.SH DESCRIPTION

Pattern_sim simulaties diffraction patterns from small crystals probed with femtosecond pulses of X-rays from a free electron laser.  Typical use might be of the form:

pattern_sim -g mydetector.geom -b my.beam -p my.pdb -r -i myintensities.hkl

The unit cell geometry will be taken from the CRYST1 line in the PDB file you provide, and the intensities of the reflections will be interpolated from the reflection list file you provide.  The reflection list format is the same as that output by process_hkl and handled by get_hkl.  You also need beam and geometry description files (-b and -g respectively).  See `man crystfel_geometry' for details of how to create a geometry file.  Examples of both files can be found in the installation directory, which is normally /usr/local/share/doc/crystfel.

The result will be written to an HDF5 file in the current directory with the name `sim.h5'.

.SH REFLECTION LISTS

pattern_sim does not know about symmetry, so your input reflection list
(give with "-i") must be expanded.  You can do this with:

$ get_hkl -i myfile.hkl -o output.hkl -y mypointgroup -e 1

Please be sure to read the "Note about Unit Cell Settings" in the documentation
for indexamajig.
