.\"
.\" process_hkl man page
.\"
.\" Copyright © 2012 Thomas White <taw@physics.org>
.\"
.\" Part of CrystFEL - crystallography with a FEL
.\"

.TH PROCESS\_HKL 1
.SH NAME
process\_hkl \- Monte Carlo merging program
.SH SYNOPSIS
.PP
.B process\_hkl
-i mypatterns.stream -o mydata.hkl -y mypointgroup [options]

.SH DESCRIPTION

This program takes as input the data stream from "indexamajig".  It merges the
many individual intensities together to form a single list of reflection
intensities which are useful for crystallography.

Typical usage is of the form:

$ process_hkl -i mypatterns.stream -o mydata.hkl -y mypointgroup

.SH CHOICE OF POINT GROUP FOR MERGING

One of the main features of serial crystallography is that the orientations of
individual crystals are random.  That means that the orientation of each
crystal must be determined independently, with no information about its
relationship to the orientation of crystals in other patterns (as would be the
case for a rotation series of patterns).

Some Laue classes are merohedral.  This means that the orientation will have an
ambiguity, but this time more serious.  The two (or more) possible
orientations could be called "twins", but the mechanism of their formation is
somewhat different to the conventional use of the term.  In these cases, you
will need to merge according to the point group corresponding holohedral Laue
class.

You can also tell process_hkl the "apparent" symmetry, which is the symmetry as
far as whatever produced the stream was concerned.  In the case of most indexing
algorithms, this will be the corresponding holohedral point group (not the
Laue class nor the holohedral Laue class).  If you use the "-a" option to give
this information, process_hkl will try to resolve the remaining orientational
ambiguities to get from the apparent symmetry to the true symmetry (given with
"-y").  Currently, it won't do a very good job of it.

The document twin-calculator.pdf contains more detailed information about this
issue, as well as tables which contain all the required information.
