#!/usr/bin/perl -w

use strict;
use File::Basename;

open(FH, $ARGV[0]);
open(TMP, "> list.tmp");

my $in_image = 0;
my $line;
my $filename;
while ( $line = <FH> ) {

	chomp $line;
	my $handled = 0;

	if ( $line =~ /^\s*[0-9\-]+\s+[0-9\-]+\s+[0-9\-]+\s+[0-9\.\-]+/ ) {
		printf(TMP "%s\n", $line);
		$handled = 1;
	}

	if ( $line =~ /^\s*[0-9\-\.]+\s+[0-9\-\.]+\s+[0-9\-\.]+\s+[0-9\.\-]+/ ) {
		printf(TMP "%s\n", $line);
		$handled = 1;
	}

	if ( $line =~ /^Reflections\ from\ indexing\ in\ (.+)$/ ) {
		$filename = $1;
		$handled = 1;
	}

	if ( $line =~ /^Peaks\ from\ peak search\ in\ (.+)$/ ) {
		$filename = $1;
		$handled = 1;
	}

	if ( $line =~ /^$/ ) {
		close(TMP);
		$filename = "images-old/".basename($filename);
		system("hdfsee ".$filename." --peak-overlay=list.tmp --binning=1 --int-boost=10");
		if ( $? != 0 ) { exit; }
		unlink("list.tmp");
		open(TMP, "> list.tmp");
		$handled = 1;
	}

	if ( !$handled ) {
		printf(STDERR "Unhandled: '%s'\n", $line);
	}

}
