#!/usr/bin/perl -w

use strict;
use File::Basename;

open(FH, $ARGV[0]);
open(TMP, "> list.tmp");

my $in_image = 0;
my $line;
my $filename;
while ( $line = <FH> ) {

	chomp $line;
	my $handled = 0;

	if ( $in_image ) {
		printf(TMP "%s\n", $line);
		$handled = 1;
	}

	if ( $line =~ /^Peaks\ from\ peak\ search$/ ) {
		$in_image = 1;
		$handled = 1;
	}

	if ( $line =~ /^Image\ filename:\ (.+)$/ ) {
		$filename = $1;
		$handled = 1;
	}

	if ( $line =~ /^End\ of\ peak\ list$/ ) {

		close(TMP);

		# Example of how to do "basename" and "prefix":
		# $filename = "images-old/".basename($filename);

		printf(STDERR "Viewing %s\n", $filename);
		system("hdfsee ".$filename.
		       " --peak-overlay=list.tmp --binning=2 --int-boost=10");
		if ( $? != 0 ) { exit; }
		unlink("list.tmp");
		open(TMP, "> list.tmp");
		$handled = 1;
		$in_image = 0;

	}

}
