#!/usr/bin/perl -w

use strict;

my $line;

printf("   h    k    l          I    phase   sigma(I)   nmeas\n");

while ( $line = <STDIN> ) {

        if ( $line =~ /([\d\-]+)\s+([\d\-]+)\s+([\d\-]+)\so\s+[\d\.\-]+\s+[\d\.\-]+\s+([\d\.\-]+)\s+([\d\.\-]+)\s+$/ ) {

                my $h = $1;
                my $k = $2;
                my $l = $3;
                my $intensity = $4;
                my $sigi = $5;

                printf("%4i %4i %4i %10.2f %s %10.2f %7i\n",
                       $h, $k, $l, $intensity, "       -", $sigi, 1);

        }

}

printf("End of reflections\n");
