#!/bin/sh

echo -------------------------------------------------------------
echo
echo In this CrystFEL version, XDS export is now done via get_hkl:
echo get_hkl -i file.hkl -p my.cell -o out.hkl --output-format=xds
echo
echo Alternatively, use the Export Data function of the CrystFEL GUI
echo
echo -------------------------------------------------------------
exit 1
