#!/bin/sh

# When you've edited the relevant parameters, delete this comment and the following two lines
echo "You need to edit this script first, to set the space group and cell parameters."
exit 1

OUTFILE=`echo $1 | sed -e 's/\.hkl$/.mtz/'`

echo " Input: $1"
echo "Output: $OUTFILE"
if [ -e create-mtz.temp.hkl -o -e $OUTFILE ]; then
	echo "   I'm about to write to the following files, but one or more"
	echo "   of them already exist:"
	echo "   " $OUTFILE
	echo "    create-mtz.temp.hkl"
	echo "   To confirm that you want to continue, which will DESTROY the"
	echo "   current contents of these files, type 'y' and press enter."
	read conf
	if [ $conf != y ]; then
		echo "Not confirmed."
		exit 1
	else
		echo "Proceeding"
		rm -f create-mtz.temp.hkl
	fi
fi

ex -c '/End of reflections/
.,$d
w create-mtz.temp.hkl
q!' $1

echo "Running 'f2mtz'..."
f2mtz HKLIN create-mtz.temp.hkl HKLOUT $OUTFILE > out.html << EOF
TITLE Reflections from CrystFEL
NAME PROJECT wibble CRYSTAL wibble DATASET wibble
CELL 100 100 100  90  90 90
SYMM P1
SKIP 3
LABOUT H K L IMEAN SIGIMEAN
CTYPE  H H H J     Q
FORMAT '(3(F4.0,1X),F10.2,10X,F10.2)'
EOF

if [ $? -ne 0 ]; then echo "Failed."; exit; fi

echo "Done."
