#!/bin/sh

OUTFILE=`echo $1 | sed -e 's/\.hkl$/.mtz/'`
TMPFILE=`echo $1 | sed -e 's/\.hkl$/.temp.mtz/'`
PDB=../1JB0.pdb

echo " Input: $1"
echo "Output: $OUTFILE"
if [ -e $TMPFILE -o -e $OUTFILE ]; then
	echo "   I'm about to write to the following files, but one or more"
	echo "   of them already exist:"
	echo "   " $TMPFILE
	echo "   " $OUTFILE
	echo "   To confirm that you want to continue, which will DESTROY the"
	echo "   current contents of these files, type 'y' and press enter."
	read conf
	if [ $conf != y ]; then
		echo "Not confirmed."
		exit 1
	else
		echo "Proceeding"
	fi
fi


# PS1: CELL 281 281 165.2  90  90 120
# PS2: CELL 139 232 309  90  90 90
# Start by putting the CrystFEL intensities into an MTZ file
echo "Running 'f2mtz'..."
f2mtz HKLIN $1 HKLOUT $TMPFILE > out.html << EOF
TITLE Reflections from CrystFEL
NAME PROJECT wibble CRYSTAL wibble DATASET wibble
CELL 139 232 309  90  90 90
SYMM P1
SKIP 1
LABOUT H K L IMEAN SIGIMEAN
CTYPE  H H H J     Q
FORMAT '(F8.0,1X,F8.0,1X,F8.0,1X,F20.2,1X,F20.2)'
EOF

if [ $? -ne 0 ]; then echo "Failed."; exit; fi

# Get the unit cell contents
echo "Running 'rwcontents'..."
rwcontents XYZIN $PDB >> out.html << EOF
NHOH 2.3 lowt
EOF

if [ $? -ne 0 ]; then echo "Failed."; exit; fi


# Run 'truncate' to turn Is into Fs
echo "Running 'truncate'..."
truncate HKLIN $TMPFILE HKLOUT $OUTFILE >> out.html << EOF
TRUNCATE NO
NOHARVEST
LABIN H=H K=K L=L IMEAN=IMEAN SIGIMEAN=SIGIMEAN
LABOUT H=H K=K L=L IMEAN=IMEAN SIGIMEAN=SIGIMEAN F=F SIGF=SIGF
CONTENTS C 16938  N 3310  O 3548  MG 96  P 3  S 89  CA 1  FE 12  H 17645
EOF

if [ $? -ne 0 ]; then echo "Failed."; exit; fi

rm -f $TMPFILE
echo "Done."
