#!/usr/bin/env python

import sys

with open(sys.argv[1]) as f:
    s = ""
    while "Begin geometry file" not in s:
        s = f.readline()
    s = f.readline()
    while "End geometry file" not in  s:
        print(s),
        s = f.readline()

