#!/usr/bin/env python
#
# Copyright © 2025 Deutsches Elektronen-Synchrotron DESY,
#                  a research centre of the Helmholtz Association.
#
# Authors:
#   2025 Thomas White <taw@physics.org>
#
# This file is part of CrystFEL.
#
# CrystFEL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CrystFEL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CrystFEL.  If not, see <http://www.gnu.org/licenses/>.

import sys
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal


f = []
g = []
n = 0

for file in sys.argv[1:]:

    if file == "-":
        fh = sys.stdin
    else:
        fh = open(file)

    for line in fh:

        f.append(float(line.strip().split(" ")[0]))
        g.append(float(line.strip().split(" ")[1]))

        n += 1
        if n%1000==0:
            sys.stdout.write("\r%i data points" % n)
            sys.stdout.flush()

    fh.close()


fn = np.asarray(f,dtype=float)
gn = np.asarray(g,dtype=float)
xn = np.arange(0, n)

sys.stdout.write("\rRead %i f-g pairs\n" % n)
sys.stdout.flush()

fig, ax = plt.subplots()

fgmin = np.minimum(fn, gn)
fgmax = np.maximum(fn, gn)
ax.set_ylim([np.mean(fgmin)-2.5*np.std(fgmin),
             np.mean(fgmax)+2.5*np.std(fgmax),])

ax.scatter(xn, gn, color='#0088ff', marker=',', s=1,
           label="Correlation coefficient in opposite orientation")
ax.scatter(xn, fn, color='#ff8800', marker=',', s=1,
           label="Correlation coefficient in correct orientation")

def smooth(p, len, bs):
    xn = []
    smoothed = []
    for x in range(0, len, bs):
        xn.append(x+bs/2)
        smoothed.append(np.mean(p[x:x+bs]))
    return xn,smoothed

bs = 500

xsmooth,fsmooth = smooth(fn, n, bs)
ax.plot(xsmooth, fsmooth, color='#ff0000', linewidth=2,
        label="Moving average correlation in correct orientation")

xsmooth,gsmooth = smooth(gn, n, bs)
ax.plot(xsmooth, gsmooth, color='#0000ff', linewidth=2,
        label="Moving average correlation in opposite orientation")

xsmooth,maxsmooth = smooth(fgmax, n, bs)
ax.plot(xsmooth, maxsmooth, color='#550000', linewidth=2,
        label="Moving average of highest correlation")

xsmooth,minsmooth = smooth(fgmin, n, bs)
ax.plot(xsmooth, minsmooth, color='#000050', linewidth=2,
        label="Moving average of lowest correlation")

ax.legend()
ax.grid(True)

plt.show()
