#!/bin/sh

./frequency.pl 103.hist > hist.dat

gnuplot << EOF
set term postscript enhanced font "Helvetica,20"
set output "histo.ps"

plot [-2000:60000] "hist.dat" u 1:2 w l t "103 reflection"
EOF

ps2pdf histo.ps
rm -f histo.ps hist.dat

evince histo.pdf
