#!/usr/bin/perl -w

use strict;

my $line;

printf("  h   k   l          I    phase   sigma(I)  1/d(nm^-1)  counts\n");

while ( $line = <STDIN> ) {

        if ( $line =~ /^\s*([\d\-]+)\s+([\d\-]+)\s+([\d\-]+)\s+([\d\.\-]+)\s+/ ) {

                my $h = $1;
                my $k = $2;
                my $l = $3;
                my $intensity = $4;

                printf("%3i %3i %3i %10.2f %s %10.2f  %10.2f %7i\n",
                       $h, $k, $l, $intensity, "       -", 0.0, 0.0, 1);

        }

}
