#!/bin/sh

# Set the installation location here
# Executables will be placed in $CFPREFIX/bin
CFPREFIX=/usr

# Set the location of syminfo.lib here
SYMINFO=/usr/local/share/ccp4/syminfo.lib

SYS=$(uname -sm)
if [ "$SYS" = "Linux x86_64" ]; then
	MOSFLM=imosflm-7.4.0-linux-64.zip
	DIRAX=dirax1.17-Linux-x86_64-static.tar.Z
	DIRAX_TAR_ARGS=-xZf
	PLATFORM="Linux x86_64"
	D=-D
fi

if [ "$SYS" = "Linux i686" ]; then
	MOSFLM=imosflm-7.4.0-linux-32.zip
	DIRAX=dirax1.17-Linux-i686-static.tar.Z
	DIRAX_TAR_ARGS=-xZf
	PLATFORM="Linux x86 (32 bit)"
	D=-D
fi

if [ "$SYS" = "Darwin x86_64" ]; then
	MOSFLM=imosflm-7.4.0-osx-64.zip
	DIRAX=dirax1.16-Darwin-x86_64.tar.gz
	DIRAX_TAR_ARGS=-xzf
	PLATFORM="MacOS x86_64"
	D=
fi

if [ "$SYS" = "Darwin arm64" ]; then
	MOSFLM=x
	DIRAX=x
	PLATFORM="MacOS ARM (Apple silicon)"
	D=
	echo I cannot install any indexers for your system.  Sorry!
	echo
	echo To install XDS, follow the instructions at https://dectris.com/en/detectors/XDS/
	exit 1
fi

if [ "x$PLATFORM" = x ]; then
	echo Could not identify your system: $SYS
	uname -a
	exit 1
fi

if [ x$1 = x--help ]; then
	echo 'This script downloads and installs Mosflm and DirAx'
	echo
	echo Step 1: $0
	echo Step 2: $0 'install    ' \# perhaps with sudo
	echo
	echo '    Installation location:' $CFPREFIX
	echo 'CCP4 syminfo.lib location:' $SYMINFO '(only needed for Mosflm)'
	echo '                 Platform:' $PLATFORM
	echo
	echo 'To alter the installation location, edit this script.'
	echo
	echo 'Please note the license conditions for each program:'
	echo '   DirAx: http://www.crystal.chem.uu.nl/distr/dirax/'
	echo '  Mosflm: https://www.mrc-lmb.cam.ac.uk/mosflm/mosflm/'
	echo
	echo Since 2026, XDS can no longer be downloaded automatically.
	echo To install XDS, follow the instructions at https://dectris.com/en/detectors/XDS/
	exit 0
fi


# Exit immediately if something doesn't work
set -e

if [ x$1 != xinstall ]; then

	if [ x$USER = xroot ]; then
		echo Do not run this as root
		exit 1
	fi

	if [ -d mosflm-tempdir -o -d dirax-tempdir ]; then
		echo Delete the following directories before trying again:
		echo mosflm-tempdir dirax-tempdir
		exit 1
	fi

	echo '    Installation location:' $CFPREFIX
	echo 'CCP4 syminfo.lib location:' $SYMINFO '(only needed for Mosflm)'
	echo '                 Platform:' $PLATFORM
	echo

	if [ x$MOSFLM != xx ]; then

		if [ ! -f $SYMINFO ]; then
			echo Cannot find SYMINFO file at $SYMINFO
			echo You need to install libCCP4
			echo ' (separately, or as part of the CrystFEL installation process)'
			echo Or, edit the script to set the correct location
			exit 1
		fi

		mkdir mosflm-tempdir
		cd mosflm-tempdir
		wget -nv https://www.mrc-lmb.cam.ac.uk/harry/imosflm/ver740/downloads/$MOSFLM
		unzip $MOSFLM imosflm/bin/mosflm
		mv imosflm/bin/mosflm mosflm.real
		echo '#!/bin/sh' > mosflm
		echo "export SYMINFO=$SYMINFO" >> mosflm
		echo "$CFPREFIX/bin/mosflm.real -n \$@" >> mosflm
		chmod +x mosflm
		cd ..
	else
		echo "Mosflm is not available for your system."
	fi

	if [ x$DIRAX != xx ]; then
		mkdir dirax-tempdir
		cd dirax-tempdir
		wget -nv http://www.crystal.chem.uu.nl/distr/dirax/download/$DIRAX
		set +e
		tar $DIRAX_TAR_ARGS $DIRAX
		if [ $? != 0 ]; then
			echo You might need to install package \'ncompress\'
			exit 1
		fi
		set -e
		mv dirax dirax.real
		echo "#!/bin/sh" > dirax
		echo "exec $CFPREFIX/bin/dirax.real \"\$@\"" >> dirax
		chmod +x dirax
		cd ..
	else
		echo Dirax is not available for your system.
	fi

	echo Now run the script again, adding \'install\' to the command line.
	echo If installing to a system location, prefix with \'sudo\'.

else

	if [ ! -f mosflm-tempdir/mosflm.real ]; then
		echo Run this script without \'install\' first
		exit 1
	fi
	set -x

	if [ -f mosflm-tempdir/mosflm ]; then
		install -b $D mosflm-tempdir/mosflm.real $CFPREFIX/bin/mosflm.real
		install -b $D mosflm-tempdir/mosflm $CFPREFIX/bin/mosflm
	fi

	if [ -f dirax-tempdir/dirax ]; then
		install -b $D dirax-tempdir/dirax dirax-tempdir/dirax.real $CFPREFIX/bin
		install -b $D -m 644 dirax-tempdir/dirax.commands $CFPREFIX/bin
	fi

fi
