#!/bin/sh

echo -------------------------------------------------------------
echo
echo In this CrystFEL version, detector geometry is altered by
echo using the new program adjust_detector.
echo
echo To move the entire detector, use the following command:
echo
echo adjust_detector -g old.geom -o new.geom -p all --shiftx=.....
echo
echo See 'man adjust_detector' for more information.
echo
echo To refine detector geometry based on indexing results, see
echo 'man align_detector'.
echo
echo -------------------------------------------------------------
exit 1
