#!/bin/sh

echo -------------------------------------------------------------
echo
echo In this CrystFEL version, MTZ import is now done via get_hkl:
echo get_hkl -i file.mtz -o out.hkl
echo
echo -------------------------------------------------------------
exit 1
