#!/bin/sh

# Rsplit_surface
#
# Plot Rsplit as a contour map
#
# Copyright © 2013 Fedor Chervinskii
# Copyright © 2013 Deutsches Elektronen-Synchrotron DESY,
#                  a research centre of the Helmholtz Association.
#
# Authors:
#   2013 Fedor Chervinskii <fedor.chervinskii@gmail.com>
#   2013 Thomas White <taw@physics.org>
#
# This file is part of CrystFEL.
#
# CrystFEL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CrystFEL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CrystFEL.  If not, see <http://www.gnu.org/licenses/>.

filename=$1
pdbfilename=$2
pg=$3

if [ x$filename = "x" -o x$pdbfilename = "x" -o x$pg = "x" ]; then
	echo "Syntax: Rsplit_surface my.stream my.pdb <point group>"
	exit 1
fi

python clean-stream.py $filename clean.stream
filename=clean.stream

LIMIT=3

for ((a=1; a <= LIMIT ; a++))
do
  let string=$a
  ./alternate-stream $filename ${filename/./1.} ${filename/./2.}
  if (($a > 1)); then
    rm $filename
  fi
  process_hkl -i ${filename/./1.} -o ${filename/.stream/1.hkl} -y $pg
  process_hkl -i ${filename/./2.} -o ${filename/.stream/2.hkl} -y $pg
  compare_hkl ${filename/.stream/1.hkl} ${filename/.stream/2.hkl} -y $pg -p ${pdbfilename} --fom=rsplit --shell-file=rsplit$string.dat
  rm ${filename/./2.}
  rm ${filename/.stream/1.hkl}
  rm ${filename/.stream/2.hkl}
  filename=${filename/.stream/1.stream}
done

rm $filename

python Rsplit_surface.py $1
