#!/bin/sh

echo $1 | ~/crystfel/src/indexamajig --indexing=dirax -i - \
                      -g ~/crystfel/examples/lcls-dec.geom \
                      -p ~/lcls/1JB0.pdb \
                      --near-bragg --filter-cm \
        | ~/crystfel/src/facetron -g ~/crystfel/examples/lcls-dec.geom
