#!/bin/sh

for FILENAME in `cat $1`; do

	echo $FILENAME | indexamajig --indexing=dirax \
	                             --near-bragg \
	                             --filter-noise \
	                             > indexed.lst

	if [ -s indexed.lst ]; then
		#hdfsee simulated.h5 &
		~/crystfel/src/hdfsee $FILENAME --binning=1 \
		                      --int-boost=8 --filter-noise \
		                      --peak-overlay=indexed.lst
	fi

	rm -f indexed.lst

done
